project:
  type: website

website:
  title: "Broadband Internet Access in the US"
  navbar:
    left:
      - text: Home
        href: index.ipynb
      - text: Background
        href: background.ipynb
      - text: Data
        href: data.ipynb
      - text: Visualizations
        href: visualizations.ipynb
      - text: Insights
        href: insights.ipynb