project:
  type: website

website:
  title: "2025 DSAN Scholarship Project"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Background
        href: background.qmd
      - text: Data
        href: data.qmd
      - text: Insights
        href: insights.qmd